# Generated by Django 3.1.6 on 2021-03-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukyul_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor_partner',
            name='sponsor_type',
            field=models.CharField(choices=[('PP', 'PRINCIPAL PARTNERS'), ('VP', 'VENUE PARTNERS'), ('MP', 'MEDIA PARTNERS'), ('PP', 'PROJECT PARTNERS'), ('SD', 'SPONSORS DIRECTORY')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
