# Generated by Django 3.1.6 on 2021-03-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukyul_app', '0002_sponsor_partner_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor_partner',
            name='sponsor_type',
            field=models.CharField(choices=[('PP', 'PRINCIPAL PARTNERS'), ('VP', 'VENUE PARTNERS'), ('MP', 'MEDIA PARTNERS'), ('PP2', 'PROJECT PARTNERS'), ('SD', 'SPONSORS DIRECTORY')], max_length=50),
        ),
    ]
